AllCops:
  TargetRubyVersion: 3.2
  NewCops: enable
  SuggestExtensions: false

Style/FrozenStringLiteralComment:
  Enabled: true
  EnforcedStyle: always

Style/StringLiterals:
  EnforcedStyle: double_quotes

Metrics/ClassLength:
  Max: 150

Metrics/AbcSize:
  Max: 30
  Exclude:
    - "test/**/*"

Metrics/CyclomaticComplexity:
  Max: 10

Metrics/PerceivedComplexity:
  Max: 12

Metrics/MethodLength:
  Max: 35
  Exclude:
    - "test/**/*"

Style/Documentation:
  Enabled: false

Lint/MissingSuper:
  Enabled: false

Naming/PredicateMethod:
  Enabled: false

Naming/VariableNumber:
  Enabled: false

Naming/FileName:
  Exclude:
    - "test/stubs/**/*"
